version: 1
update_configs:
- package_manager: "java:maven"
  directory: "/"
  update_schedule: "weekly"
  default_reviewers:
    - "oleg-nenashev"
    - "jglick"
  ignored_updates:
    - match:
        dependency_name: "org.jenkins-ci.main:jenkins-core"
    - match:
        dependency_name: "org.jenkins-ci.main:jenkins-war"
    # Avoid bumping plugins for self-testing, there is PCT which shoud be used for newest versions
    - match:
        dependency_name: "org.jenkins-ci.plugins*"
    - match:
        dependency_name: "io.jenkins.plugins*"
    #TBD: Jetty?
